In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset_path = "../resources/dataset/dataset_mfccs.csv"
df = pd.read_csv(dataset_path)

In [3]:
df.head()

Unnamed: 0                                            feature class_label
0           0  [-190.01157    102.312195   -16.247314    20.9...      ataque
1           1  [ -96.46623     90.81202    -59.434887    47.4...    resposta
2           2  [-298.91815     137.08705     -30.425154     5...      ataque
3           3  [-1.31611053e+02  1.02911446e+02 -4.95664177e+...      ataque
4           4  [-1.40606369e+02  1.20304314e+02  1.57993755e+...      ataque

In [4]:
df['feature'][0]

'[-190.01157    102.312195   -16.247314    20.979342    -7.56885\n    5.987731   -21.88395      1.1568208  -25.370169    -6.3788652\n  -10.03191     -1.8490307  -14.903505     3.5276108   -9.699297\n   -4.6201525   -8.37393      4.115322   -17.340166    -4.5524597\n -105.07515     65.86336    -68.669945    21.78145    -16.206589\n    1.0608407  -20.418653    15.675302   -21.640686     1.4477832\n  -14.121458     2.3777814  -23.332413     7.798055   -13.541649\n    0.6554884   -7.1016545    9.495931   -26.04744      0.9626331]'

In [5]:
a = np.fromstring(df['feature'][0][1:-1], dtype=np.float, sep=' ')
a

array([-190.01157  ,  102.312195 ,  -16.247314 ,   20.979342 ,
         -7.56885  ,    5.987731 ,  -21.88395  ,    1.1568208,
        -25.370169 ,   -6.3788652,  -10.03191  ,   -1.8490307,
        -14.903505 ,    3.5276108,   -9.699297 ,   -4.6201525,
         -8.37393  ,    4.115322 ,  -17.340166 ,   -4.5524597,
       -105.07515  ,   65.86336  ,  -68.669945 ,   21.78145  ,
        -16.206589 ,    1.0608407,  -20.418653 ,   15.675302 ,
        -21.640686 ,    1.4477832,  -14.121458 ,    2.3777814,
        -23.332413 ,    7.798055 ,  -13.541649 ,    0.6554884,
         -7.1016545,    9.495931 ,  -26.04744  ,    0.9626331])

In [6]:
# Apply a lambda function to each column
df['feature'] = df['feature'].apply(lambda x : np.fromstring(x[1:-1], dtype=np.float, sep=' '))

In [7]:
# Só garantindo que tem 40 mfccs em todos
print(df['feature'][0].shape == (40,))
for a in df['feature']:
    if(a.shape != (40,)):
        print(a)

True


In [8]:
df.head()

Unnamed: 0                                            feature class_label
0           0  [-190.01157, 102.312195, -16.247314, 20.979342...      ataque
1           1  [-96.46623, 90.81202, -59.434887, 47.461735, -...    resposta
2           2  [-298.91815, 137.08705, -30.425154, 51.051403,...      ataque
3           3  [-131.611053, 102.911446, -49.5664177, 51.9903...      ataque
4           4  [-140.606369, 120.304314, 15.7993755, 25.64609...      ataque

In [9]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

# Convert features and corresponding classification labels into numpy arrays
X = np.array(df.feature.tolist())
y = np.array(df.class_label.tolist())

# Encode the classification labels
le = LabelEncoder()
yy = to_categorical(le.fit_transform(y))

Using TensorFlow backend.
/home/moutinho/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/moutinho/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/moutinho/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/moutinho/.local/lib/python3.6/site-packages/tensorflo

In [10]:
X

array([[-190.01157   ,  102.312195  ,  -16.247314  , ...,    9.495931  ,
         -26.04744   ,    0.9626331 ],
       [ -96.46623   ,   90.81202   ,  -59.434887  , ...,   -3.9965458 ,
          -7.29263   ,   -1.0455719 ],
       [-298.91815   ,  137.08705   ,  -30.425154  , ...,   -8.919206  ,
          -2.13994   ,   -7.7758036 ],
       ...,
       [ -80.1168671 ,   84.3639145 ,  -53.2616539 , ...,  -12.0656633 ,
           4.78937864,  -15.9731112 ],
       [-293.4313    ,  123.83074   ,  -22.08263   , ...,    1.8079743 ,
         -14.64967   ,   -0.47940993],
       [-260.14926   ,   95.26475   ,    7.120217  , ...,    4.8389626 ,
         -10.432459  ,    1.5442473 ]])

In [11]:
# split the dataset 
from sklearn.model_selection import train_test_split 

x_train, x_test, y_train, y_test = train_test_split(X, yy, test_size=0.2, random_state = 127)

In [12]:
print(yy.shape[1])
print(yy.shape)
print(yy)
print("--------------")
print(X.shape)
print(X)

2
(2148, 2)
[[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]
--------------
(2148, 40)
[[-190.01157     102.312195    -16.247314   ...    9.495931
   -26.04744       0.9626331 ]
 [ -96.46623      90.81202     -59.434887   ...   -3.9965458
    -7.29263      -1.0455719 ]
 [-298.91815     137.08705     -30.425154   ...   -8.919206
    -2.13994      -7.7758036 ]
 ...
 [ -80.1168671    84.3639145   -53.2616539  ...  -12.0656633
     4.78937864  -15.9731112 ]
 [-293.4313      123.83074     -22.08263    ...    1.8079743
   -14.64967      -0.47940993]
 [-260.14926      95.26475       7.120217   ...    4.8389626
   -10.432459      1.5442473 ]]


In [13]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import Adam
from keras.utils import to_categorical

num_labels = yy.shape[1]
filter_size = 2

def build_model_graph(input_shape=(40,)):
    model = Sequential()
    model.add(Dense(256))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(256))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(num_labels))
    model.add(Activation('softmax'))
    # Compile the model
    model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

    return model

model = build_model_graph()

In [14]:
from keras.callbacks import ModelCheckpoint 
from datetime import datetime 

num_epochs = 200
num_batch_size = 64

model.fit(x_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(x_test, y_test), verbose=1)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Train on 1718 samples, validate on 430 samples
Epoch 1/200
1718/1718 [==============================] - 1s 610us/step - loss: 6.3382 - accuracy: 0.5471 - val_loss: 6.0557 - val_accuracy: 0.5279
Epoch 2/200
1718/1718 [==============================] - 0s 89us/step - loss: 5.9022 - accuracy: 0.5629 - val_loss: 5.7748 - val_accuracy: 0.5628
Epoch 3/200
1718/1718 [==============================] - 0s 85us/step - loss: 5.9124 - accuracy: 0.5733 - val_loss: 6.8221 - val_accuracy: 0.5349
Epoch 4/200
1718/1718 [==============================] - 0s 81us/step - loss: 6.1911 - accuracy: 0.5483 - val_loss: 7.0113 - val_accuracy: 0.5279
Epoch 5/200
1718/1718 [==============================] - 0s 83us/step - loss: 5.7621 - accuracy: 0.5821 - val_loss: 7.0304 - val_accuracy: 0.5256
Epoch 6/200
1718/1718 [==============================] - 0s 85us/step - loss: 6.1165 - accuracy: 0.5693 - val_loss: 6.9633 - va

1718/1718 [==============================] - 0s 126us/step - loss: 0.6776 - accuracy: 0.5960 - val_loss: 0.6873 - val_accuracy: 0.5349
Epoch 53/200
1718/1718 [==============================] - 0s 136us/step - loss: 0.6782 - accuracy: 0.5937 - val_loss: 0.6872 - val_accuracy: 0.5326
Epoch 54/200
1718/1718 [==============================] - 0s 98us/step - loss: 0.6692 - accuracy: 0.5931 - val_loss: 0.6852 - val_accuracy: 0.5326
Epoch 55/200
1718/1718 [==============================] - 0s 98us/step - loss: 0.6625 - accuracy: 0.5978 - val_loss: 0.6850 - val_accuracy: 0.5326
Epoch 56/200
1718/1718 [==============================] - 0s 132us/step - loss: 0.6701 - accuracy: 0.6065 - val_loss: 0.6856 - val_accuracy: 0.5326
Epoch 57/200
1718/1718 [==============================] - 0s 96us/step - loss: 0.6827 - accuracy: 0.5943 - val_loss: 0.6875 - val_accuracy: 0.5279
Epoch 58/200
1718/1718 [==============================] - 0s 133us/step - loss: 0.6747 - accuracy: 0.5873 - val_loss: 0.6851 - v

1718/1718 [==============================] - 0s 95us/step - loss: 0.6214 - accuracy: 0.6490 - val_loss: 0.6848 - val_accuracy: 0.5558
Epoch 108/200
1718/1718 [==============================] - 0s 99us/step - loss: 0.6152 - accuracy: 0.6513 - val_loss: 0.6886 - val_accuracy: 0.5535
Epoch 109/200
1718/1718 [==============================] - 0s 88us/step - loss: 0.6255 - accuracy: 0.6426 - val_loss: 0.6841 - val_accuracy: 0.5698
Epoch 110/200
1718/1718 [==============================] - 0s 92us/step - loss: 0.6112 - accuracy: 0.6478 - val_loss: 0.6890 - val_accuracy: 0.5558
Epoch 111/200
1718/1718 [==============================] - 0s 82us/step - loss: 0.6131 - accuracy: 0.6659 - val_loss: 0.6876 - val_accuracy: 0.5674
Epoch 112/200
1718/1718 [==============================] - 0s 80us/step - loss: 0.6189 - accuracy: 0.6391 - val_loss: 0.6935 - val_accuracy: 0.5581
Epoch 113/200
1718/1718 [==============================] - 0s 83us/step - loss: 0.6134 - accuracy: 0.6525 - val_loss: 0.6941 -

1718/1718 [==============================] - 0s 91us/step - loss: 0.5314 - accuracy: 0.7148 - val_loss: 0.8416 - val_accuracy: 0.5837
Epoch 163/200
1718/1718 [==============================] - 0s 119us/step - loss: 0.5124 - accuracy: 0.7212 - val_loss: 0.8412 - val_accuracy: 0.5767
Epoch 164/200
1718/1718 [==============================] - 0s 144us/step - loss: 0.5235 - accuracy: 0.7357 - val_loss: 0.7984 - val_accuracy: 0.5744
Epoch 165/200
1718/1718 [==============================] - 0s 90us/step - loss: 0.5269 - accuracy: 0.7165 - val_loss: 0.8104 - val_accuracy: 0.5488
Epoch 166/200
1718/1718 [==============================] - 0s 89us/step - loss: 0.5233 - accuracy: 0.7235 - val_loss: 0.8613 - val_accuracy: 0.5814
Epoch 167/200
1718/1718 [==============================] - 0s 89us/step - loss: 0.5372 - accuracy: 0.7159 - val_loss: 0.7838 - val_accuracy: 0.5744
Epoch 168/200
1718/1718 [==============================] - 0s 93us/step - loss: 0.5103 - accuracy: 0.7375 - val_loss: 0.8368

In [15]:
# Evaluating the model on the training and testing set
score = model.evaluate(x_train, y_train, verbose=0)
print("Training Accuracy: {0:.2%}".format(score[1]))

score = model.evaluate(x_test, y_test, verbose=0)
print("Testing Accuracy: {0:.2%}".format(score[1]))

Training Accuracy: 84.40%
Testing Accuracy: 56.51%


In [16]:
# serialize model to JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk


In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 256)               10496     
_________________________________________________________________
activation_1 (Activation)    (None, 256)               0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 256)               65792     
_________________________________________________________________
activation_2 (Activation)    (None, 256)               0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 2)                

In [18]:
76802*4

307208