In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset_path = "../resources/dataset/dataset_mfccs.csv"
df = pd.read_csv(dataset_path)

In [3]:
df.head()

Unnamed: 0                                            feature class_label
0           0  [-190.01157    102.312195   -16.247314    20.9...      ataque
1           1  [ -96.46623     90.81202    -59.434887    47.4...    resposta
2           2  [-298.91815     137.08705     -30.425154     5...      ataque
3           3  [-1.31611053e+02  1.02911446e+02 -4.95664177e+...      ataque
4           4  [-1.40606369e+02  1.20304314e+02  1.57993755e+...      ataque

In [4]:
df['feature'][0]

'[-190.01157    102.312195   -16.247314    20.979342    -7.56885\n    5.987731   -21.88395      1.1568208  -25.370169    -6.3788652\n  -10.03191     -1.8490307  -14.903505     3.5276108   -9.699297\n   -4.6201525   -8.37393      4.115322   -17.340166    -4.5524597\n -105.07515     65.86336    -68.669945    21.78145    -16.206589\n    1.0608407  -20.418653    15.675302   -21.640686     1.4477832\n  -14.121458     2.3777814  -23.332413     7.798055   -13.541649\n    0.6554884   -7.1016545    9.495931   -26.04744      0.9626331]'

In [5]:
a = np.fromstring(df['feature'][0][1:-1], dtype=np.float, sep=' ')
a

array([-190.01157  ,  102.312195 ,  -16.247314 ,   20.979342 ,
         -7.56885  ,    5.987731 ,  -21.88395  ,    1.1568208,
        -25.370169 ,   -6.3788652,  -10.03191  ,   -1.8490307,
        -14.903505 ,    3.5276108,   -9.699297 ,   -4.6201525,
         -8.37393  ,    4.115322 ,  -17.340166 ,   -4.5524597,
       -105.07515  ,   65.86336  ,  -68.669945 ,   21.78145  ,
        -16.206589 ,    1.0608407,  -20.418653 ,   15.675302 ,
        -21.640686 ,    1.4477832,  -14.121458 ,    2.3777814,
        -23.332413 ,    7.798055 ,  -13.541649 ,    0.6554884,
         -7.1016545,    9.495931 ,  -26.04744  ,    0.9626331])

In [6]:
# Apply a lambda function to each column
df['feature'] = df['feature'].apply(lambda x : np.fromstring(x[1:-1], dtype=np.float, sep=' '))

In [7]:
# Só garantindo que tem 40 mfccs em todos
print(df['feature'][0].shape == (40,))
for a in df['feature']:
    if(a.shape != (40,)):
        print(a)

True


In [8]:
df.head()

Unnamed: 0                                            feature class_label
0           0  [-190.01157, 102.312195, -16.247314, 20.979342...      ataque
1           1  [-96.46623, 90.81202, -59.434887, 47.461735, -...    resposta
2           2  [-298.91815, 137.08705, -30.425154, 51.051403,...      ataque
3           3  [-131.611053, 102.911446, -49.5664177, 51.9903...      ataque
4           4  [-140.606369, 120.304314, 15.7993755, 25.64609...      ataque

In [9]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical

# Convert features and corresponding classification labels into numpy arrays
X = np.array(df.feature.tolist())
y = np.array(df.class_label.tolist())

# Encode the classification labels
le = LabelEncoder()
yy = to_categorical(le.fit_transform(y))

Using TensorFlow backend.
/home/moutinho/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/moutinho/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/moutinho/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/moutinho/.local/lib/python3.6/site-packages/tensorflo

In [10]:
X

array([[-190.01157   ,  102.312195  ,  -16.247314  , ...,    9.495931  ,
         -26.04744   ,    0.9626331 ],
       [ -96.46623   ,   90.81202   ,  -59.434887  , ...,   -3.9965458 ,
          -7.29263   ,   -1.0455719 ],
       [-298.91815   ,  137.08705   ,  -30.425154  , ...,   -8.919206  ,
          -2.13994   ,   -7.7758036 ],
       ...,
       [ -80.1168671 ,   84.3639145 ,  -53.2616539 , ...,  -12.0656633 ,
           4.78937864,  -15.9731112 ],
       [-293.4313    ,  123.83074   ,  -22.08263   , ...,    1.8079743 ,
         -14.64967   ,   -0.47940993],
       [-260.14926   ,   95.26475   ,    7.120217  , ...,    4.8389626 ,
         -10.432459  ,    1.5442473 ]])

In [11]:
# split the dataset 
from sklearn.model_selection import train_test_split 

x_train, x_test, y_train, y_test = train_test_split(X, yy, test_size=0.2, random_state = 127)

In [12]:
print(yy.shape[1])
print(yy.shape)
print(yy)
print("--------------")
print(X.shape)
print(X)

2
(2148, 2)
[[1. 0.]
 [0. 1.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]
--------------
(2148, 40)
[[-190.01157     102.312195    -16.247314   ...    9.495931
   -26.04744       0.9626331 ]
 [ -96.46623      90.81202     -59.434887   ...   -3.9965458
    -7.29263      -1.0455719 ]
 [-298.91815     137.08705     -30.425154   ...   -8.919206
    -2.13994      -7.7758036 ]
 ...
 [ -80.1168671    84.3639145   -53.2616539  ...  -12.0656633
     4.78937864  -15.9731112 ]
 [-293.4313      123.83074     -22.08263    ...    1.8079743
   -14.64967      -0.47940993]
 [-260.14926      95.26475       7.120217   ...    4.8389626
   -10.432459      1.5442473 ]]


In [13]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import Adam
from keras.utils import to_categorical

num_labels = yy.shape[1]
filter_size = 2

def build_model_graph(input_shape=(40,)):
    model = Sequential()
    model.add(Dense(256))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(256))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(num_labels))
    model.add(Activation('softmax'))
    # Compile the model
    model.compile(loss='binary_crossentropy', metrics=['accuracy'], optimizer='adam')

    return model

model = build_model_graph()

In [14]:
from keras.callbacks import ModelCheckpoint 
from datetime import datetime 

num_epochs = 200
num_batch_size = 64

model.fit(x_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(x_test, y_test), verbose=1)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Train on 1718 samples, validate on 430 samples
Epoch 1/200
1718/1718 [==============================] - 2s 1ms/step - loss: 8.5158 - accuracy: 0.4342 - val_loss: 8.1187 - val_accuracy: 0.4721
Epoch 2/200
1718/1718 [==============================] - 2s 1ms/step - loss: 8.7996 - accuracy: 0.4278 - val_loss: 8.1187 - val_accuracy: 0.4721
Epoch 3/200
1718/1718 [==============================] - 2s 1ms/step - loss: 8.7996 - accuracy: 0.4278 - val_loss: 8.1187 - val_accuracy: 0.4721
Epoch 4/200
1718/1718 [==============================] - 2s 1ms/step - loss: 8.7996 - accuracy: 0.4278 - val_loss: 8.1187 - val_accuracy: 0.4721
Epoch 5/200
1718/1718 [==============================] - 2s 1ms/step - loss: 8.7996 - accuracy: 0.4278 - val_loss: 8.1187 - val_accuracy: 0.4721
Epoch 6/200
1718/1718 [==============================] - 2s 1ms/step - loss: 8.7996 - accuracy: 0.4278 - val_loss: 8.1187 - val_accur

KeyboardInterrupt: 

In [ ]:
# Evaluating the model on the training and testing set
score = model.evaluate(x_train, y_train, verbose=0)
print("Training Accuracy: {0:.2%}".format(score[1]))

score = model.evaluate(x_test, y_test, verbose=0)
print("Testing Accuracy: {0:.2%}".format(score[1]))